Repository Hina39/HyperInverter, pull requests merged in 2023-11, with the labels that each got.

#1 Feat/add docker
  environments/Dockerfile
  environments/gpu/docker-compose.yaml
  poetry.lock
  poetry.toml
  pyproject.toml
Labels: ちょあ

#2 :smile: memo desu
  .gitignore
  configs/paths_config.py
  models/hyper_inverter.py
  sample_scripts/train_human_faces.sh
Labels: ちょあ

#3 :cake: add makefile
  Makefile
  poetry.lock
  pyproject.toml
Labels: ちょあ

#5 chore: refactor redundant files
  .github/ISSUE_TEMPLATE/development.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  models/hyper_inverter.py
  requirements.txt
Labels: ちょあ

#8 feat: add save latent
  .gitignore
  scripts/save_latent.py
  utils/common.py
Labels: enhancement

#10 fix: save-latent.py.
  scripts/save_latent.py
Labels: bug

#11 fix: quick fix for generate_from_latent.py
  scripts/generate_from_latent.py
Labels: bug

#12 Refactor/clean up
  options/test_options.py
  poetry.lock
  pyproject.toml
  scripts/generate_from_latent.py
  scripts/save_latent.py
Labels: ちょあ
